name: Build binance_prover binaries

on:
  push:
    paths:
      - 'tlsn/examples/binance/**'
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: ubuntu-24.04
            binary_suffix: ubuntu_noble
            target: x86_64-unknown-linux-gnu
          - os: macos-14
            binary_suffix: macos_sonoma
            target: x86_64-apple-darwin
          - os: macos-14
            binary_suffix: macos_sonoma_arm64
            target: aarch64-apple-darwin

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: ${{ matrix.target }}

      - name: Install Rust target
        run: rustup target add ${{ matrix.target }}

      - name: Build binance_prover
        run: |
          cd tlsn
          cargo build --release --example binance_prover --target ${{ matrix.target }}

      - name: Archive binary
        run: |
          mkdir -p artifacts
          cp tlsn/target/${{ matrix.target }}/release/examples/binance_prover artifacts/binance_prover_${{ matrix.binary_suffix }}

      - name: Display structure of downloaded files
        run: ls -R artifacts

      - name: Get current timestamp for tag
        id: timestamp
        run: echo "tag_name=binance_prover_$(date +'%Y%m%d%H%M%S')" >> $GITHUB_ENV

      - name: Create git tag
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git tag ${{ env.tag_name }}
          git push origin ${{ env.tag_name }}
        env:
          tag_name: ${{ env.tag_name }}

      - name: Create release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ env.tag_name }}
          release_name: "Release ${{ env.tag_name }}"
          body: |
            ## Binaries
            - binance_prover_ubuntu_noble
            - binance_prover_macos_sonoma
            - binance_prover_macos_sonoma_arm64
          draft: false
          prerelease: false
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Release Assets
        run: |
          gh release upload ${{ env.tag_name }} \
            artifacts/binance_prover_ubuntu_noble.zip \
            artifacts/binance_prover_macos_sonoma.zip \
            artifacts/binance_prover_macos_sonoma_arm64.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

