name: Build Binance Prover Binaries

on:
  push:
    paths:
      - 'tlsn/examples/binance/**'
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, macos-latest]
        target: [x86_64-unknown-linux-gnu, aarch64-apple-darwin, x86_64-apple-darwin]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: ${{ matrix.target }}

      - name: Build project
        run: cargo build --release --example binance_prover --target ${{ matrix.target }}

      - name: Archive binary
        run: |
          mkdir -p artifacts/${{ matrix.os }}-${{ matrix.target }}
          cp target/${{ matrix.target }}/release/binance_prover artifacts/${{ matrix.os }}-${{ matrix.target }}/binance_prover

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: binance_prover
          path: artifacts/${{ matrix.os }}-${{ matrix.target }}/

