name: Build Binance Prover Binaries

on:
  push:
    paths:
      - 'tlsn/examples/binance/**'
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: ubuntu-24.04
          - os: ubuntu-22.04
          - os: macos-14
          - os: macos-14-arm64

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: ${{ matrix.target }}

      - name: Build binance_prover
        run: |
          cd tlsn
          cargo build --release --example binance_prover

      - name: Archive binary
        run: |
          mkdir -p artifacts/${{ matrix.os }}
          cp tlsn/target/release/examples/binance_prover artifacts/${{ matrix.os }}/binance_prover

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: binance_prover
          path: artifacts/${{ matrix.os }}/
          compression-level: 9

