name: Create release
on:
  workflow_run:
    workflows: [Build binance_prover binaries]
  workflow_dispatch:

jobs:
  create-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Get current timestamp for tag
        id: timestamp
        run: echo "tag_name=binance_prover_$(date +'%Y%m%d%H%M%S')" >> $GITHUB_ENV

