name: Create release
on:
  workflow_run:
    workflows: [Build binance_prover binaries]
  workflow_dispatch:

jobs:
  create-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Get current timestamp for tag
        id: timestamp
        run: echo "tag_name=binance_prover_$(date +'%Y%m%d%H%M%S')" >> $GITHUB_ENV

      - name: Create Git Tag
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git tag ${{ env.tag_name }}
          git push origin ${{ env.tag_name }}
        env:
          tag_name: ${{ env.tag_name }}

      - name: Download Build Artifacts
        uses: actions/download-artifact@v3
        with:
          name: binance_prover_ubuntu_noble
          path: artifacts/binance_prover_ubuntu_noble.zip

      - name: Upload macOS Sonoma Binary
        uses: actions/download-artifact@v3
        with:
          name: binance_prover_macos_sonoma
          path: artifacts/binance_prover_macos_sonoma.zip

      - name: Upload macOS Sonoma ARM64 Binary
        uses: actions/download-artifact@v3
        with:
          name: binance_prover_macos_sonoma_arm64
          path: artifacts/binance_prover_macos_sonoma_arm64.zip

      - name: Create GitHub Release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ env.tag_name }}
          release_name: "Release ${{ env.tag_name }}"
          body: |
            ## Binaries
            - binance_prover_ubuntu_noble
            - binance_prover_macos_sonoma
            - binance_prover_macos_sonoma_arm64
          draft: false
          prerelease: false
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Release Assets
        run: |
          gh release upload ${{ env.tag_name }} \
            artifacts/binance_prover_ubuntu_noble.zip \
            artifacts/binance_prover_macos_sonoma.zip \
            artifacts/binance_prover_macos_sonoma_arm64.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
